TensorFlow-Free Data Loader
geoelements/gns pull request #13
Opened 2022-02-15 22:51 UTC by jpvantassel

# In this PR

- ✨ Convert .tfrecord format training data to .npz format.
- ✨ Create tensorflow-free dataloader. Data loader can handle any number of training simulations of arbitrary length.
- 🚧 Early work on distributed training framework.

2022-02-16 14:40 UTC, kks32 reviewed
If we are not calling distribute.py in this version, could we not include it and wait until we have it completed? Then, we can merge?

2022-02-18 15:29 UTC, jpvantassel commented
> If we are not calling distribute.py in this version, could we not include it and wait until we have it completed? Then, we can merge?

`distribute.py` has been removed.

2022-02-18 15:40 UTC, jpvantassel commented
> This is wonderful! Thanks @jpvantassel
> 
>     * Could you add some info in the README about the format of `.npz` files?
> 
>     * I don't see a convertor you mentioned for TFRecord to .npz

Notes on the PyTorch dataloader and npz format has been added to README.

Mention was in relation to the conversion of tfrecord to npz; there is no converter.
The branch tfrecord_to_npy includes details on the transformation.

2022-02-18 15:46 UTC, kks32 commented on gns/data_loader.py
> +        positions = np.transpose(positions, (1, 0, 2)) # nparticles, input_sequence_length, dimension
This will only work for 2D? Can we keep this as an input argument?

Also, the number of particles?

2022-02-19 16:01 UTC, kks32 requested changes
Other than the question about hardcoding the particle dimension, I'm good.

2022-03-07 19:48 UTC, jpvantassel commented
> Could we generalize the data loader for `nparticles` and `dim`?

Done, see c406410

2022-03-08 16:20 UTC, jpvantassel commented
> Other than the question about hardcoding the particle dimension, I'm good.

2022-04-19 16:50 UTC, kks32 approved these changes

2022-04-19 16:50 UTC, merged