add a doc for explaining details about training data
geoelements/gns pull request #59
Opened 2023-08-16 02:56 UTC by yjchoi1

**Describe the PR**
Added doc for explaining details about training data

**Related Issues/PRs**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.

2023-08-16 12:10 UTC, kks32 requested changes
Starting with Python 3.10, ragged version of arrays is not supported. How should we change the format so that we can continue to support `npz` formats?

2023-08-17 14:50 UTC, yjchoi1 commented
The current data structure used in meshnet (dictionary-based) works fine with the up-to-date numpy and python 3.10.

2023-08-17 16:27 UTC, kks32 requested changes

2023-08-17 16:27 UTC, kks32 commented on docs/flow_data.md
> +# About `pos`
These should be subheadings. 
```suggestion
## `pos`
```

2023-08-17 16:27 UTC, kks32 commented on docs/flow_data.md
> +# About `node_type`
```suggestion
## `node_type`
```

2023-08-17 16:27 UTC, kks32 commented on docs/flow_data.md
> +# About `cells`
```suggestion
## `cells`
```

2023-08-18 03:57 UTC, yjchoi1 commented
The suggestion has been committed.

2023-08-18 04:28 UTC, kks32 approved these changes

2023-08-18 04:28 UTC, merged