frontera virtual env script
geoelements/gns pull request #69
Opened 2024-03-21 14:21 UTC by leilaroshan

Added a script to create a virtual environment on Frontera CPU and GPU nodes.

2024-03-22 04:33 UTC, kks32 requested changes

2024-03-22 04:33 UTC, kks32 commented on build_venv_frontera.sh
> +source module.sh
since you already loaded the modules, why do oyou need this?

2024-03-22 04:33 UTC, kks32 commented on build_venv_frontera.sh
> +which python
remove this

2024-03-22 04:33 UTC, kks32 commented on build_venv_frontera.sh
> +python3 -m gns.train --data_path="./gns-sample/WaterDropSample/dataset/" --model_path="../models/" --output_path="../output/"  -ntraining_steps=100
don't include this in the build env.

2024-03-22 04:33 UTC, kks32 commented on build_venv_frontera.sh
> +echo 'which python -> venv'
Add a command line argument and run tests only if it is set to true.

2024-03-22 12:53 UTC, leilaroshan commented
The modifications have been applied to the "build_venv_frontera.sh" file.

2024-03-22 13:19 UTC, leilaroshan commented on build_venv_frontera.sh
> +python3 test/test_torch_geometric.py
Now It's all moved to the "Testing" section.

2024-03-22 14:43 UTC, kks32 commented on build_venv_frontera.sh
> +which python
```suggestion

```

2024-03-22 14:44 UTC, kks32 requested changes
Minor visual edits

2024-03-22 14:44 UTC, kks32 commented on build_venv_frontera.sh
> +
```suggestion
```

2024-03-23 01:31 UTC, kks32 approved these changes
Great job @leilaroshan ! Congrats on your first PR!

2024-03-23 01:31 UTC, merged